AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/migrate/20171004090643_devise_create_users.rb'
    - 'db/schema.rb'
    - 'spec/spec_helper.rb'
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
