env:
  global:
    - CC_TEST_REPORTER_ID=76eed05e22f7780b13bf629b671e49fb2a0f79acd82f614e8ef6d6f27cf070cc
language: ruby
rvm:
  - 2.4
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE karakoram_test;'
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - bundle install --jobs=3 --retry=3
  - yarn
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
