# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ed7c5729bef1475649a5340862aa96500f15c519337e8dcc00b43de0b6490bf4309619307afea074a98e0a4599a795cc2744c9628f144376bcf2ca774a40c605

  telegram:
    bot:
      token: <%= ENV['BOT_TOKEN'] %>
      username: iCampus_bot

test:
  secret_key_base: 0f8aabc588af2f2eaaef929d68689c63548b25035353de84f44aec4f3fa0efa1d5df31fc13864dedffd0e3c7dfd4d64acadf9ac695018f338525d35a89690093

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
